volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/jdagoy/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/jdagoy/data/wordpress
      o: bind
  homepage:
    driver: local
    driver_opts:
      type: none
      device: /home/jdagoy/data/homepage
      o: bind

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:jdagoy
    depends_on:
      - wordpress
      - website
    volumes:
      - wordpress:/var/www/wordpress
      - homepage:/var/www/homepage
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    profiles:
      - mandatory
      - bonus
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:jdagoy
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - ../secrets/.env
    networks:
      - inception
    restart: always
    profiles:
      - mandatory
      - bonus
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:jdagoy
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ../secrets/.env
    networks:
      - inception
    restart: always
    profiles:
      - mandatory
      - bonus
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    build: ./requirements/redis_bonus
    image: redis:jdagoy
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    profiles:
      - bonus
  
  ftp:
    container_name: ftp
    build: ./requirements/ftp_bonus
    image: ftp:jdagoy
    depends_on:
      - wordpress
    volumes:
      - wordpress:/home/jdagoy/ftp/files
    env_file:
      - ../secrets/.env
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"  # Passive FTP port range
    networks:
      - inception
    restart: always
    profiles:
      - bonus

  website:
    container_name:  website
    build: ./requirements/website_bonus
    image: website:jdagoy
    volumes:
      - homepage:/var/www/homepage
    networks:
      - inception
    restart: always
    profiles:
      - bonus

  adminer:
    container_name: adminer
    build: ./requirements/adminer_bonus
    image: adminer:jdagoy
    depends_on:
      - wordpress
    ports:
      - "42:80"
    networks:
      - inception
    restart: always
    profiles:
      - bonus
