services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ../secrets/.env
    networks:
      - inception
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - ../secrets/.env
    networks:
      - inception
    restart: always
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/jdagoy/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/jdagoy/data/wordpress

networks:
  inception:
    name: inception