volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/jdagoy/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/jdagoy/data/wordpress
      o: bind
  homepage:
    driver: local
    driver_opts:
      type: none
      device: /home/jdagoy/data/homepage
      o: bind
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jdagoy/data/prometheus
      o: bind

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:jdagoy
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
      - homepage:/var/www/homepage
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    profiles:
      - mandatory
      - bonus
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:jdagoy
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - ../secrets/.env
    networks:
      - inception
    restart: always
    profiles:
      - mandatory
      - bonus
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:jdagoy
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ../secrets/.env
    networks:
      - inception
    restart: always
    profiles:
      - mandatory
      - bonus

  redis:
    container_name: redis
    build: ./requirements/redis_bonus
    image: redis:jdagoy
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
    profiles:
      - bonus

  website:
    container_name: website
    build: ./requirements/website_bonus
    image: website:jdagoy
    volumes:
      - homepage:/var/www/homepage
    networks:
      - inception
    restart: always
    profiles:
      - bonus

  adminer:
    container_name: adminer
    build: ./requirements/adminer_bonus
    image: adminer:jdagoy
    depends_on:
      - wordpress
    env_file:
      - ../secrets/.env
    ports:
      - "80:80"
    networks:
      - inception
    restart: always
    profiles:
      - bonus

  prometheus:
    container_name: prometheus
    build: ./requirements/prometheus_bonus
    image: prometheus:jdagoy
    volumes:
      - prometheus_data:/monitor
    env_file:
      - ../secrets/.env
    ports:
      - "9090:9090"
    networks:
      - inception
    restart: unless-stopped
    profiles:
      - bonus

  cadvisor:
    container_name: cadvisor
    build: ./requirements/cadvisor_bonus
    image: cadvisor:jdagoy
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception
    ports:
      - "8080:8080"
    restart: unless-stopped
    profiles:
      - bonus

  grafana:
    container_name: grafana
    build: ./requirements/grafana_bonus
    image: grafana:jdagoy
    volumes:
      - prometheus_data:/monitor
    networks:
      - inception
    ports:
      - "3000:3000"
    env_file:
      - ../secrets/.env
    restart: unless-stopped
    profiles:
      - bonus