volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/jdagoy/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/jdagoy/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:jdagoy
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:jdagoy
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - ../secrets/.env
    networks:
      - inception
    restart: always
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:jdagoy
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ../secrets/.env
    networks:
      - inception
    restart: always
    # healthcheck:
    #   test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
